version: 2.1

executors:
  docker-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install Docker client"
          command: |
            apt-get update && apt-get install -y docker.io
            docker --version
      - run:
          name: "Authenticate with Google Cloud"
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev
      - run:
          name: "Build Docker Image"
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/$GKE_CLUSTER_REPO/celebrity-app:latest .
      - run:
          name: "Push Docker Image"
          command: |
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/$GKE_CLUSTER_REPO/celebrity-app:latest

  deploy_to_gke:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: "Update package list"
          command: |
            apt-get update
      - run:
          name: "Install kubectl"
          command: |
            apt-get install -y kubectl
      - run:
          name: "Authenticate with Google Cloud"
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
      - run:
          name: "Configure GKE"
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      - run:
          name: "Deploy to GKE"
          command: |
            kubectl apply -f kubernetes-deployment.yaml --validate=false
            kubectl rollout restart deployment/celebrity-app
      - run:
          name: "Verify deployment"
          command: |
            kubectl get deployments
            kubectl get pods -l app=celebrity-app

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image